services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Pushp@m009
      MYSQL_DATABASE: cv
    ports:
      - "3308:3306"
    networks:
      - app_network

  streamlit:
    build: .
    container_name: streamlit_app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306  # use container's internal port
      MYSQL_USER: root
      MYSQL_PASSWORD: Pushp@m009
      MYSQL_DB: cv
    ports:
      - "8503:8501"
    networks:
      - app_network
    depends_on:
      - mysql

networks:
  app_network:
    driver: bridge
